### ISSUE TITLE
Getting a crash when running CryptoNets' test.py with NGRAPH_ENCRYPT_MODEL=1

### ISSUE THREAD

**Issue by r-kellerm** [NervanaSystems/he-transformer#129]
Hi,

Trying to run the following command causes a crash -
```
NGRAPH_ENCRYPT_MODEL=1 [NGRAPH_TF_BACKEND=HE_SEAL_CKKS | NGRAPH_TF_BACKEND=HE_SEAL_BFV]  python test.py
```
(with or without NGRAPH_HE_SEAL_CONFIG) 
However it doesn't happen when both NGRAPH_ENCRYPT_MODEL and NGRAPH_ENCRYPT_DATA are specified.
There is a crash as in the following log:

(venv-tf-py3) he-transformer/examples/cryptonets$ NGRAPH_ENCRYPT_MODEL=1 NGRAPH_TF_BACKEND=HE_SEAL_BFV python test.py
TensorFlow version installed: 1.12.0 (v1.12.0-0-ga6d8ffa)
nGraph bridge built with: 1.12.0 (v1.12.0-0-ga6d8ffa)
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
[INFO] 2019-01-20T13:36:01z src/seal/bfv/he_seal_bfv_backend.cpp 65	Using SEAL BFV default parameters
[INFO] 2019-01-20T13:36:01z src/seal/ckks/he_seal_ckks_backend.cpp 83	Using SEAL CKKS default parameters
[INFO] 2019-01-20T13:36:01z src/seal/ckks/he_seal_ckks_backend.cpp 87	Error config_path is NULL
[INFO] 2019-01-20T13:36:01z src/seal/ckks/he_seal_ckks_backend.cpp 88	Error using NGRAPH_HE_SEAL_CONFIG. Using default 
[INFO] 2019-01-20T13:36:01z src/seal/he_seal_util.hpp 33	
/ Encryption parameters:
| scheme: HE:SEAL:BFV
| poly_modulus: 4096
| coeff_modulus size: 109 bits
| plain_modulus: 1024
\ noise_standard_deviation: 3.2
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 258	Encrypting model
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 324	[ Parameter_0 ]
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 329	Parameter shape {1, 784}
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 324	[ Constant_17 ]
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 450	Inputs: 
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 458	Outputs: Cipher
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 402	Constant_17 took 110ms
[INFO] 2019-01-20T13:36:01z src/he_backend.cpp 324	[ Constant_14 ]
[INFO] 2019-01-20T13:36:02z src/he_backend.cpp 450	Inputs: 
[INFO] 2019-01-20T13:36:02z src/he_backend.cpp 458	Outputs: Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Constant_14 took 9896ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Constant_10 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: 
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Constant_10 took 0ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Constant_3 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: 
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Constant_3 took 14ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Reshape_2 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: Plain
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Plain
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 786	Reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 801	Done with reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Reshape_2 took 0ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Reshape_5 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 786	Reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 801	Done with reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Reshape_5 took 0ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Reshape_4 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: Plain
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Plain
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 786	Reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 801	Done with reshape op
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 402	Reshape_4 took 0ms
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 324	[ Convolution_6 ]
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 450	Inputs: Plain, Cipher
[INFO] 2019-01-20T13:36:11z src/he_backend.cpp 458	Outputs: Cipher
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborted (core dumped)

**Comment by fboemer** [comment]
I see the same behavior, with the error message
```[INFO] 2019-01-28T21:44:42z src/he_backend.cpp 331	[ Convolution_6 ]
[INFO] 2019-01-28T21:44:42z src/he_backend.cpp 467	Inputs: Plain, Cipher
[INFO] 2019-01-28T21:44:42z src/he_backend.cpp 475	Outputs: Cipher
[INFO] 2019-01-28T21:44:42z src/seal/kernel/convolution_seal.hpp 85	Convolution output size 720
terminate called after throwing an instance of 'std::invalid_argument'
terminate called recursively
  what():  plain_ntt cannot be zeroterminate called recursively
terminate called recursively

terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
[1]    370680 abort      NGRAPH_ENCRYPT_MODEL=1 NGRAPH_TF_BACKEND=HE_SEAL_CKKS python test.py
```
The `plain_ntt cannot be zero` is a result of https://github.com/Microsoft/SEAL/blob/aa7bf57aa11a91d9ca8712816550ae68793add99/src/seal/evaluator.cpp#L2709
which disallows multiplication by a plaintext 0.

Try passing in `NGRAPH_OPTIMIZED_MULT=1` to avoid this multiplication.

Note, you will exceed the multiplicative depth budget of the default configuration, unless you pass in a `NGRAPH_HE_SEAL_CONFIG `.
