### ISSUE TITLE
NameError: name 'prev' is not defined

### ISSUE THREAD

**Issue by luoxiaolin521** [NervanaSystems/he-transformer#130]
install he-transformer
after run "make -j install",the problem is 
![image](https://user-images.githubusercontent.com/19303546/51724412-249ba580-2055-11e9-9021-c7a2be980aaf.png)

**Comment by fboemer** [comment]
I suspect you might have a virtual environment active. Before building, try deactivating any active virtual environments, i.e. run `deactivate`.

**Comment by 27tech** [comment]
Have the same issue under docker build 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/17887031/52212290-c9f41c00-2894-11e9-981a-b2715abc20eb.png">

**Comment by 27tech** [comment]
@luoxiaolin521 solved by specifying virtualenv version
```bash
pip3 install virtualenv==16.1.0
```

**Comment by Arman001** [comment]
Installing virtualenv version 16.1.0 worked for me too thanks. :)
