### ISSUE TITLE
Ubuntu gets stucked after running make -j install 

### ISSUE THREAD

**Issue by Arman001** [NervanaSystems/he-transformer#136]
I have tried to install he-transformer again and again but after building it gets stuck at **96%**, when I run command **make -j install** in build directory.

**Comment by fboemer** [comment]
You may have an Out of Memory error; try installing with `make install`. Some steps of the process will take longer than others.

**Comment by Arman001** [comment]
Thank you very much for your quick response, at least now I am out of that stuck issue. make install worked. Now I am facing other errors. :)
