### ISSUE TITLE
Ubuntu 18 stucks after long number compilings at tensorflow compiling.

### ISSUE THREAD

**Issue by Arman001** [NervanaSystems/he-transformer#142]
When I run 
**cmake .. [-DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7]**
and then
**make install**  it stucked on tensorflow compiling. 
![image](https://user-images.githubusercontent.com/21517793/54191811-79e22800-44d8-11e9-86c7-6faf315ad4e2.png)

And when I skip compiling of tensorflow with
**cmake .. -DUSE_PREBUILT_BINARIES=ON [-DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7]**
It gives error of tensorflow not being in there.

Kindly help me out here . Thank you!

**Comment by fboemer** [comment]
I suspect you may be running out of memory. Would you check `htop` or similar for OutOfMemory processes? The `-DUSE_PREBUILT_BINARIES=ON` flag only works once you have completed the first `make install`, so the error is expected

**Comment by Arman001** [comment]
Yes, I think you are right about that, but if I run this on a higher end pc will it work then? Because then it should not be out of memory.

**Comment by Arman001** [comment]
Maybe I can kill the high memory process with some auto script but again it will fail all the process.

**Comment by fboemer** [comment]
A machine with more memory should help; it looks like Tensorflow [supports](https://www.tensorflow.org/install/source) a `--local_resources` flag to help low-memory machines. This isn't currently supported in ngraph-tensorflow. (see line https://github.com/NervanaSystems/ngraph-tf/blob/master/build_ngtf.py#L202); feel free to open an issue there if this remains a problem

**Comment by Arman001** [comment]
Thank you very much for your help, I will check it out.

**Comment by Arman001** [comment]
Can any one please tell how much time it really takes to compile all files ?

**Comment by fboemer** [comment]
It takes me about 30 minutes for a fresh build on a large machine

**Comment by Arman001** [comment]
Thank you it took near 3 hours on my laptop when other error came.
