### ISSUE TITLE
Error running make -j4 install

### ISSUE THREAD

**Issue by Arman001** [NervanaSystems/he-transformer#143]
Again another problem is here about mkl it automatically tries to find mkl from a repository but cant. I have installed mkl by manual but still giving errors. Kindly help me here Thank you
![Screenshot from 2019-03-15 06-12-13](https://user-images.githubusercontent.com/21517793/54412106-71ad0700-46e9-11e9-95dd-b5551e00951d.png)

**Comment by fboemer** [comment]
This looks like an issue with [ng-tf](https://github.com/NervanaSystems/ngraph-tf). Feel free to open an issue there.

**Comment by Arman001** [comment]
I will and thank you for your feedback.
