### ISSUE TITLE
Makefile:129: recipe for target 'all' failed

### ISSUE THREAD

**Issue by Arman001** [NervanaSystems/he-transformer#145]
I used a more powerful machine but again stuck in another error. Kindly help me here
Thankyou!
![image](https://user-images.githubusercontent.com/21517793/54489854-9ca67f00-48d2-11e9-91e7-bdac82be0fae.png)

**Comment by fboemer** [comment]
The screenshot you show doesn't have the reason for the failure. You'll have to look up further (or try `make` again) to see.

**Comment by Arman001** [comment]
Thanks, you were right about that doing everything all again with a fresh clone worked for me. Interestingly this time I did not get ngraph-tf error but now I am stuck at libseal.a not found. Though this should have been built automatically. 
![image](https://user-images.githubusercontent.com/21517793/54497893-f2eede80-4921-11e9-9036-379e5e4bf3c6.png)

**Comment by fboemer** [comment]
This seems to stem from [here](https://github.com/NervanaSystems/he-transformer/blob/master/cmake/seal.cmake#L51-L54). Which part of the `~/ext_ngraph_tf/src/ext_ngraph_tf/build/.../ngraph_bridge/libseal.a` doesn't exist (any intermediate folder, or just the final `libseal.a`?

**Comment by Arman001** [comment]
Thanks for the reply, I think the problem here is python version which I have python3.6. So, the folder created is of 3.6 instead of 3.5 though no libseal.a is in this also. I am trying it with python3.5 now.

**Comment by Arman001** [comment]
Will I think the genuine issue is again of ngraph_tf which I have also opened on https://github.com/NervanaSystems/ngraph-tf/issues/457

**Comment by brettdewar1** [comment]
Hey guys. I think my issue is similar. Any thoughts??
![Ubuntu error](https://user-images.githubusercontent.com/52397119/68451965-fe8e6d00-0244-11ea-9728-e73087c168da.png)

**Comment by Arman001** [comment]
I am not expert at this but the problem with mine installation was that I was using a newer version of python so it was not creating the same folder.  So, when installation time comes it gave me error. Its better to go with thier custom recommended versions of installation.
