### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by luoxiaolin521** [NervanaSystems/he-transformer#170]
When i run the command of MNIST-Cryptonets:
NGRAPH_ENCRYPT_DATA=1 NGRAPH_BATCH_DATA=1 NGRAPH_HE_SEAL_CONFIG=../../test/model/he_seal_ckks_config_N13_L7.json NGRAPH_TF_BACKEND=HE_SEAL_CKKS python test.py --batch_size=4096
i encounter this error:
![image](https://user-images.githubusercontent.com/19303546/57756681-48a5f400-76e3-11e9-8af2-75839ee048a6.png)
What's wrong?

**Comment by fboemer** [comment]
The json parse error likely means `../../test/model/he_seal_ckks_config_N13_L7.json` is not a (valid) file
