### ISSUE TITLE
undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)

### ISSUE THREAD

**Issue by luoxiaolin521** [NervanaSystems/he-transformer#171]
When I install he-transformer by “make install”，i encounter this error：
![image](https://user-images.githubusercontent.com/19303546/57923691-8006d300-7892-11e9-9d8c-0231b22a67de.png)

**Comment by fboemer** [comment]
This might be an issue with CXX_ABI. Try setting gcc-7 / g++-7 to the default
