### ISSUE TITLE
-- Could NOT find Boost CMake Error at cmake/boost.cmake:24 (message):   Boost not found

### ISSUE THREAD

**Issue by liao1230ho123** [NervanaSystems/he-transformer#177]
Hi there, I'm new to Linux.I have gcc version 7.4.0 and cmake 3.10.2 and I keep getting this error.
![image](https://user-images.githubusercontent.com/39261494/58383478-f5e50a00-8009-11e9-8646-8995905c9dcd.png)

**Comment by fboemer** [comment]
You'll need to add boost to your path, see the [Dockerfile](https://github.com/NervanaSystems/he-transformer/blob/master/docker/Dockerfile.he-transformer#L59-L61) for hints on how to do this

**Comment by liao1230ho123** [comment]
Hello, thanks for your reply. I followed the steps in Dockerfile, and I add the path of boost_1_69_0 to .bashrc  file. However the same error still occurs,  is there any other solution?

**Comment by liao1230ho123** [comment]
thanks, it works, but here comes the new issue,  could you take a time look at this, it will be very helpful.
![image](https://user-images.githubusercontent.com/39261494/58492152-ef3dca80-81a2-11e9-8eaf-153b69723a34.png)
