### ISSUE TITLE
error while using sudo make install python_wheel

### ISSUE THREAD

**Issue by liao1230ho123** [NervanaSystems/he-transformer#207]
Hi, I successfully done the step of make install, and I was trying the client mode using seal_client.
While I try to use command sudo make install python_wheel in "build" folder ,this error occurs.
![image](https://user-images.githubusercontent.com/39261494/59276490-f67bd280-8c90-11e9-81c4-b8a5bc2b95bd.png)
 
Any help?  Thanks so much.

**Comment by fboemer** [comment]
Not sure what's the problem here. You could try setting an install prefix (i.e. run `cmake .. -DCMAKE_INSTALL_PREFIX=~/mylibs`). Then you wouldn't need sudo to `make install` and `make install python_wheel`

**Comment by liao1230ho123** [comment]
Thanks for your reply, It seems to work but now getting

**Comment by liao1230ho123** [comment]
Thanks for your reply, it seems to work but now getting another error.
![image](https://user-images.githubusercontent.com/39261494/59280801-bfa9ba80-8c98-11e9-9256-d57d296cabe3.png)

using pip got same result
Any help

**Comment by fboemer** [comment]
The name of the wheel `cp27` suggests it was built for python2.7. Try activating the virtualenv *before* doing the `make install python_wheel`. This should create a `cp35` wheel (for python3.5), which you can then install in the virtualenv.

**Comment by liao1230ho123** [comment]
After I make install python_wheel , I try to import he_seal_client
but I encounter this error , Very appreciate for your help
![image](https://user-images.githubusercontent.com/39261494/59293172-39e63900-8cb1-11e9-96d2-01a275608595.png)

**Comment by liao1230ho123** [comment]
I found the libngraph.so is in one of the folder in build 
I try to add  
export LD_LIBRARY_PATH=/home/liao/het-ransformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/python/ngraph_bridge:$LD_LIBRARY_PATH
to bashrc file and source it
It worked to use python3 ( not active source external/venv-tf-py3/bin/activate)
![image](https://user-images.githubusercontent.com/39261494/59300697-66ef1780-8cc2-11e9-900b-04919ac8ff66.png)
![image](https://user-images.githubusercontent.com/39261494/59300713-6f475280-8cc2-11e9-9d3f-1f5fa3b41848.png)

but to active source external/venv-tf-py3/bin/activate
still occurs the same error  
Any suggestions wold be very appreciated

**Comment by fboemer** [comment]
The LD_LIBRARY_PATH should be unnecessary after #211
