### ISSUE TITLE
error while using client mode

### ISSUE THREAD

**Issue by liao1230ho123** [NervanaSystems/he-transformer#210]
I used 
export LD_LIBRARY_PATH=/home/liao/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/python/ngraph_bridge:$LD_LIBRARY_PATH
while active virtualenv and it finally found libngraph.so
After that I tried to use client mode 
client shows : 
![image](https://user-images.githubusercontent.com/39261494/59340573-d30c6280-8d38-11e9-9d15-02165c5183b2.png)
![image](https://user-images.githubusercontent.com/39261494/59340618-eb7c7d00-8d38-11e9-8dfb-dbe7e0d81486.png)

another terminal shows : 
![image](https://user-images.githubusercontent.com/39261494/59340666-ffc07a00-8d38-11e9-99b0-fc33295c5a55.png)

**Comment by fboemer** [comment]
Thank you for pointing this out. This should be fixed in #211

**Comment by liao1230ho123** [comment]
Hi, Im new to Git, what exactly should I do ?  Rebuild all from source code?

**Comment by fboemer** [comment]
Git pull and then rebuild (run the cmake command, and the make install commands). If you run into issues, starting a fresh build (i.e. remove build directory and create a new one) might help
