### ISSUE TITLE
error while running pyclient_mnist.py

### ISSUE THREAD

**Issue by liao1230ho123** [NervanaSystems/he-transformer#212]
running pyclient.py gets
![image](https://user-images.githubusercontent.com/39261494/59403122-03550f00-8dd4-11e9-822f-97d8637fcf72.png)
seems alright

but running pyclient_mnist.py gets this error 
![image](https://user-images.githubusercontent.com/39261494/59403144-1bc52980-8dd4-11e9-9ac4-1971e2b1e0a4.png)
![image](https://user-images.githubusercontent.com/39261494/59403158-2da6cc80-8dd4-11e9-86fe-bedeaa41f32d.png)

any suggestion would be appreciated

**Comment by liao1230ho123** [comment]
this might seems like the processes itself acquires lots of memory ? for almost 14000000015 bytes of memory?

**Comment by liao1230ho123** [comment]
sometimes it runs through the error and get this 
client : 
![image](https://user-images.githubusercontent.com/39261494/59425583-d1aa6b00-8e08-11e9-9d4e-44af0e3e6363.png)

![image](https://user-images.githubusercontent.com/39261494/59425568-c9523000-8e08-11e9-8a38-53e02335be4a.png)

server 
![image](https://user-images.githubusercontent.com/39261494/59425614-e1c24a80-8e08-11e9-9080-213bcc28de4e.png)
![image](https://user-images.githubusercontent.com/39261494/59425636-eab31c00-8e08-11e9-8da3-3927e870ebee.png)

Not sure this is the right result

**Comment by fboemer** [comment]
1) The client-server model indeed currently requires ~14GB data, as needed to support MobileNetV2, where the encrypted input is almost that large. (See https://github.com/NervanaSystems/he-transformer/blob/master/src/tcp/tcp_message.hpp#L123). Until we get a more elegant solution in place, the easiest way to work on limited-memory systems is by changing the 14000000000UL value to a smaller one.
2) For debugging purposes, you can also disable the client-server, perhaps that will require less memory as well.

**Comment by liao1230ho123** [comment]
After changing the value to 12000000000UL 
get this result   I think its correct
![image](https://user-images.githubusercontent.com/39261494/59439062-278e0b80-8e27-11e9-9088-252ecf87af8e.png)
![image](https://user-images.githubusercontent.com/39261494/59439090-32e13700-8e27-11e9-93c6-4b52582dcdde.png)
