### ISSUE TITLE
HE_SEAL should be HE_SEAL_CKKS

### ISSUE THREAD

**Issue by rsandler00** [NervanaSystems/he-transformer#222]
Hi,

I tried running the basic example in `examples/axpy.py` using the line `NGRAPH_TF_BACKEND=HE_SEAL python axpy.py` as indicated in `examples/README.md`. However I got the error:

```
tensorflow.python.framework.errors_impl.InternalError: NGRAPH_TF_BACKEND: HE_SEAL is not supported
```

I could only get it to work by using `NGRAPH_TF_BACKEND=HE_SEAL_CKKS python axpy.py`. (Note HE_SEAL_**CKKS**)

Is there a typo here or am I doing something wrong?

**Comment by fboemer** [comment]
We previously used the `HE_SEAL_CKKS` flag. If you rebuild from master, it should work with `HE_SEAL`

**Comment by rsandler00** [comment]
Got it . Thanks!
