### ISSUE TITLE
Demoing Encryption Capabilities

### ISSUE THREAD

**Issue by liv-daliberti** [NervanaSystems/he-transformer#224]
Hello,

I have successfully installed the library, including the python bindings. I've tested the MNIST example, and the ax.py example and I think I have a pretty fair understanding of how it all works (having read the nGraph-HE paper, the CKKS algorithm paper, and taken a look at the Microsoft SEAL Github account). 

However, I was wondering if there were some way to view the encrypted data/models? I recognize that the data is being encrypted and then decrypted, but I can't seem to figure out how to view the encrypted data (or the keys, encryptors, and decryptors) without editing the c++ libraries on the backend in the src file area. 

Is there a way to do this for demo purposes using python?

Thank you!

**Comment by fboemer** [comment]
Unfortunately we don't have a python wrapper, so you'd have to edit the C++ files.

**Comment by liv-daliberti** [comment]
Should I be editing the he_seal_executable.cpp file, or will it require me to go in and edit the headerfiles too?

Thank you for the quick replie

**Comment by fboemer** [comment]
`he_seal_executable.cpp` basically tracks the various tensors used in the DL model and maps them to the ops. It depends on what exactly you'd like to do. Feel free to email me (fabian.boemer@intel.com) if you have more questions

**Comment by liv-daliberti** [comment]
I sent you a message at my work email. Thank you very much.

**Comment by jayavanth** [comment]
Sorry to resurrect this thread. Which functions in that file should I look at to get the encrypted data? Also, are there plans to expose python APIs?
