### ISSUE TITLE
Should this be compiled on Intel CPU? Mine is AMD which occurs cpu_backend problems.

### ISSUE THREAD

**Issue by xjiao004** [NervanaSystems/he-transformer#225]

**Comment by fboemer** [comment]
The CPUBackend is for Intel CPU (see [here](https://github.com/NervanaSystems/ngraph/blob/master/ecosystem-overview.md)). Unfortunately, we currently don't have a way to build without building the CPU backend.

**Comment by xjiao004** [comment]
> The CPUBackend is for Intel CPU (see [here](https://github.com/NervanaSystems/ngraph/blob/master/ecosystem-overview.md)). Unfortunately, we currently don't have a way to build without building the CPU backend.

Okay, got it. Thanks for for your help. So if need to compile on AMD, should get PlaidML first?

**Comment by fboemer** [comment]
Not sure; feel free to ask at [ngraph](https://github.com/NervanaSystems/ngraph). In theory, mkl-dnn supports AMD, so it should be possible to run the CPUBackend.
