### ISSUE TITLE
Getting error for basic matrix multiplication example

### ISSUE THREAD

**Issue by rsandler00** [NervanaSystems/he-transformer#226]
I want to implement basic matrix multiplication in nGRAPH-HE. 

Below is my code: 

```
import ngraph_bridge
import numpy as np
import tensorflow as tf

tBf32 = tf.placeholder(np.float32)

def matmul(a, b, c = None):

    # Code will only run in 'encrypted mode' if a constant bias is used
    if c is None:
        z = tf.constant(np.zeros(shape=(a.shape[0], b.shape[1])), dtype=np.float32)
    else:
        z = tf.constant(c, dtype=np.float32)
		
    za = tf.constant(a, dtype=np.float32)
    with tf.Session() as sess:
        return sess.run(z + tf.matmul(za, tBf32), {tBf32: b})


if __name__ == '__main__':
    for _ in range(10):
        a = np.random.randint(low = -8, high = 8, size=(20,20))
        b = np.random.randint(low = -1, high = 1, size=(20,20))
        c = np.random.uniform(size=(20,20)) * 2
        d = np.abs(matmul(a, b, c) - (np.matmul(a, b) + c))
        print('Maximum error is {}'.format(np.max(d)))
```

The above code is run via: `NGRAPH_ENCRYPT_DATA=1 NGRAPH_TF_BACKEND=HE_SEAL python tm.py`

I am running into 2 issues:
1) An offset needs to be provided for the multiplication to work in encrypted mode (e.g.  `return sess.run(tf.matmul(za, tBf32), {tBf32: b})` will nt perform encryption. In fact, the bias specifically needs to be before the matmul, so this will not work either: `return sess.run(tf.matmul(za, tBf32) + z, {tBf32: b})`
2) This program worked in a previous commit (6ae29aa1898eaba62b677d13ec4570e159b30ab7); however, in the latest release I get a error when running it:

```
2019-07-01 12:20:06.131850: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2019-07-01 12:20:06.134584: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3936000 executing computations on platform Host. Devices:
2019-07-01 12:20:06.134640: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
[INFO] 2019-07-01T19:20:06z src/seal/he_seal_encryption_parameters.hpp 110      Using default SEAL CKKS parameters
[WARN] 2019-07-01T19:20:06z src/seal/he_seal_backend.cpp 57     Parameter selection does not enforce minimum security level
/
| Encryption parameters :
|   scheme: CKKS
|   poly_modulus_degree: 1024
|   coeff_modulus size: 150 (30 + 30 + 30 + 30 + 30) bits
\
[INFO] 2019-07-01T19:20:06z src/seal/he_seal_backend.cpp 84     Scale 1.0737e+09
[INFO] 2019-07-01T19:20:06z src/seal/he_seal_executable.cpp 462 Batching data with batch size 20
[INFO] 2019-07-01T19:20:06z src/seal/he_seal_executable.cpp 479 Processing server inputs
*** Error in `python3': free(): invalid next size (fast): 0x00007f486c000ba0 ***
*** Error in `python3': free(): invalid next size (fast): 0x00007f4854000ba0 ***
*** Error in `python3': free(): invalid next size (fast): 0x00007f4814000ba0 ***
*** Error in `python3': free(): invalid next size (fast): 0x00007f4894000ba0 ***
Aborted (core dumped)
```

**Comment by fboemer** [comment]
Thank you for the detailed report.

1) I believe with simple enough expressions, TF evaluates them directly, rather than passing to the HE backend. Adding the bias seems to complicate the expression enough that the backend is used.

2) This is the result of enabling SIMD packing along the batch axes by default. https://github.com/NervanaSystems/he-transformer/pull/228 adds a flag to disable this packing. Once you add this commit, you should be able to call `NGRAPH_UNPACK_DATA=1 NGRAPH_ENCRYPT_DATA=1 NGRAPH_TF_BACKEND=HE_SEAL python tm.py`

**Comment by rsandler00** [comment]
> Thank you for the detailed report.
> 
> 1. I believe with simple enough expressions, TF evaluates them directly, rather than passing to the HE backend. Adding the bias seems to complicate the expression enough that the backend is used.
> 2. This is the result of enabling SIMD packing along the batch axes by default. #228 adds a flag to disable this packing. Once you add this commit, you should be able to call `NGRAPH_UNPACK_DATA=1 NGRAPH_ENCRYPT_DATA=1 NGRAPH_TF_BACKEND=HE_SEAL python tm.py`

Got it. This worked. Thanks!
