### ISSUE TITLE
Error converting preexisting TF graph

### ISSUE THREAD

**Issue by rsandler00** [NervanaSystems/he-transformer#227]
Hi, 

I am trying to convert the TF graph in my existing codebase to be HE compatible with nGRAPH-HE. 

To convert it I replaced all non-HE compatible layers w/ HE compatible versions, and added `import ngraph_bridge` to the top of the file. 

To run the program I use: `NGRAPH_TF_BACKEND=HE_SEAL python make_basic_net.py`

However, I get an error:

```
<personal program printout>
/
| Encryption parameters :
|   scheme: CKKS
|   poly_modulus_degree: 8192
|   coeff_modulus size: 180 (30 + 24 + 24 + 24 + 24 + 24 + 30) bits
\
[INFO] 2019-07-01T21:58:47z src/seal/he_seal_backend.cpp 84     Scale 1.67608e+07
[INFO] 2019-07-01T21:58:48z src/seal/he_seal_executable.cpp 462 Batching data with batch size 3
[INFO] 2019-07-01T21:58:48z src/seal/he_seal_executable.cpp 479 Processing server inputs
2019-07-01 14:58:48.016521: I /home/isi/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/src/ngraph_utils.cc:252] Serializing graph to: tf_function_error_ngraph_cluster_45.json

Traceback (most recent call last):
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: Check '(element_type == element::f32)' failed at /home/isi/he-transformer/src/seal/kernel/constant_seal.cpp:27:
Constant supports only f32 type


         [[{{node ngraph_cluster_45}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_basic_net.py", line 80, in <module>
    out = tfnet.sess.run(tfnet.out, {tfnet.inp: input})
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/isi/projects/VORGNet/.venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: Check '(element_type == element::f32)' failed at /home/isi/he-transformer/src/seal/kernel/constant_seal.cpp:27:
Constant supports only f32 type
```

At first I thought there was something wrong with my graph, but then I tried debugging by inputting data to the 1st layer, getting the output and feeding that output to the next layer, and then repeating until I went through the whole network. Lo and behold, every layer in isolation successfully worked. It is only when they are combined that it gives this error. 

_________________________________________________________
Other debugging attempts:

1) I tried running with NGRAPH_ENCRYPT_DATA=1 (eg: `GRAPH_ENCRYPT_DATA=1 NGRAPH_TF_BACKEND=HE_SEAL python make_basic_net.py`). I have no idea what this flag does as I thought encrypting data is the default behavior? In either case, this time I got a different error (see below). Furthermore, I got the same error when I tried running the layers in isolation. 

```
/
| Encryption parameters :
|   scheme: CKKS
|   poly_modulus_degree: 8192
|   coeff_modulus size: 180 (30 + 24 + 24 + 24 + 24 + 24 + 30) bits
\
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_backend.cpp 84     Scale 1.67608e+07
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 459 Encrypting data
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 462 Batching data with batch size 3
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 479 Processing server inputs
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 504 Encrypting parameter 0
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 519 Done encrypting parameter
[INFO] 2019-07-01T22:00:39z src/seal/he_seal_executable.cpp 504 Encrypting parameter 0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

2) I also tried building from a previous commit (6ae29aa1898eaba62b677d13ec4570e159b30ab7 - see [my other issue](https://github.com/NervanaSystems/he-transformer/issues/226)), and got the exact same behaviour.

**Comment by fboemer** [comment]
Hi,
* the error "Constant supports only f32 type" is because we currently only support float32 types. Let me know if you aren't able to work around this and we may be able to add support for int32, int64.

* The `NGRAPH_ENCRYPT_DATA=1` will encrypt the data, and is *not* the default. Without this flag, the network will run on plaintext (albeit slowly due to naive implementation). The `bad_alloc` error suggests you are running out of memory. How large of a model are you trying to run; how much memory do you have?

**Comment by rsandler00** [comment]
Thanks @fboemer!

To respond to the 1st point, as far as I can tell all the variables in the model are f32 types. This was confirmed when I tried to use all the layers independently and the error did not come up. That is why I think this is a bug and not a misusage.

**Comment by fboemer** [comment]
Would you check the serialized output file `tf_function_error_ngraph_cluster_45.json`? There should be a non-float constant node in there. It may be subtle, perhaps the result of a `shape_size` call or similar.

**Comment by fboemer** [comment]
You may also try unpacking the data (see https://github.com/NervanaSystems/he-transformer/issues/226)

**Comment by rsandler00** [comment]
Thanks @fboemer! I think the issue was a training/testing flag. I recreated the network from scratch (w/o/ relying on my previous codebase) and I was able to get everything working
