### ISSUE TITLE
ngraph::CheckFailure error when loading keras model with tensorflow backend

### ISSUE THREAD

**Issue by work-hard-play-harder** [NervanaSystems/he-transformer#236]
I trained a keras model with tensorflow backend. Everything works well without importing ngraph_bridge package. 

But when I imported ngraph-bridge package and load the keras model. I got the following errors. I built the he-transformer-0.5.0 on ubuntu 18.04 with python 3.6. 

I just use the load_model function to load the trained model.
```python
model_name = 'models/checkpoint_NoneActivation_1k.01-0.8113.h5'
autoencoder = load_model(model_name)

autoencoder.summary()
```

(venv-tf-py3) jchen67@ubuntu:~/Downloads/he-transformer-0.5.0/examples/MyProject$ NGRAPH_ENCRYPT_DATA=1 NGRAPH_HE_SEAL_CONFIG=../../test/model/he_seal_ckks_config_N13_L7.json NGRAPH_TF_BACKEND=HE_SEAL python load_keras_model.py 
WARNING:tensorflow:From /home/jchen67/Downloads/he-transformer-0.5.0/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-07-17 13:38:06.146089: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3490765000 Hz
2019-07-17 13:38:06.146441: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x406edd0 executing computations on platform Host. Devices:
2019-07-17 13:38:06.146488: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
/
| Encryption parameters :
|   scheme: CKKS
|   poly_modulus_degree: 8192
|   coeff_modulus size: 180 (30 + 24 + 24 + 24 + 24 + 24 + 30) bits
\
[INFO] 2019-07-17T17:38:06z src/seal/he_seal_backend.cpp 84	Scale 1.67608e+07
[INFO] 2019-07-17T17:38:06z src/seal/he_seal_executable.cpp 459	Encrypting data
[INFO] 2019-07-17T17:38:06z src/seal/he_seal_executable.cpp 462	Batching data with batch size 1
[INFO] 2019-07-17T17:38:06z src/seal/he_seal_executable.cpp 479	Processing server inputs
[INFO] 2019-07-17T17:38:06z src/seal/he_seal_executable.cpp 504	Encrypting parameter 0
[INFO] 2019-07-17T17:38:08z src/seal/he_seal_executable.cpp 519	Done encrypting parameter
[INFO] 2019-07-17T17:38:08z src/seal/he_seal_executable.cpp 504	Encrypting parameter 0
[INFO] 2019-07-17T17:38:10z src/seal/he_seal_executable.cpp 519	Done encrypting parameter
[INFO] 2019-07-17T17:38:14z src/seal/he_seal_executable.cpp 663	Total time 4120 (ms) 
[INFO] 2019-07-17T17:38:14z src/seal/he_seal_executable.cpp 459	Encrypting data
[INFO] 2019-07-17T17:38:14z src/seal/he_seal_executable.cpp 462	Batching data with batch size 1
[INFO] 2019-07-17T17:38:14z src/seal/he_seal_executable.cpp 479	Processing server inputs
[INFO] 2019-07-17T17:38:14z src/seal/he_seal_executable.cpp 504	Encrypting parameter 0
terminate called after throwing an instance of 'ngraph::CheckFailure'
  what():  Check '(values.size() >= m_batch_size)' failed at /home/jchen67/Downloads/he-transformer-0.5.0/src/he_plain_tensor.cpp:105:
values size 0 is smaller than batch size 1

terminate called recursively
terminate called recursively
Aborted (core dumped)

Do you guys have any ideas? I will appreciate if you give me any suggestions.

**Comment by fboemer** [comment]
The error happens when you call the summary method? It seems calling the `summary()` method invokes the inference commmand with zero-sized inputs. The simplest work-around might be to just `import ngraph_bridge` after the `summary()` method.

**Comment by work-hard-play-harder** [comment]
Thank you @fboemer .  When I remove the `summary()` method, it sill has the same error. So the error should be due to the `load_model` method. 

As your suggestion, it works when I `import ngraph_bridge` after the `summary()` method. 
But for now, I got a new error `terminate called after throwing an instance of 'std::bad_alloc' ` which should because I have not enough memory. 
I will let you know, when I solved this issue.

Thank you so much.

**Comment by work-hard-play-harder** [comment]
I still can't make keras code work on HE-transformer. 

I rebuilt the latest HE-transformer on ubuntu 18.04. The keras version is '2.2.4'. I used the mnist_cnn tutorial in Keras document ( https://keras.io/examples/mnist_cnn/ ).

It looks good when I import ngraph_bridge after the `summary()` method.
But I always got the same issue `Segmentation fault (core dumped)` when I predicted test data using loaded model. 

I am exhausted on this issue. I am very appreciated if you guys could provide an example based on keras?

**Comment by fboemer** [comment]
After looking into this, I suspect you ran into the following issues:
* The `std::bad_alloc` message is not due to running out of memory, but rather an array access past the end of a tensor in the broadcast operation. Set `NGRAPH_VOPS=all` to see more debugging output. The reason for this:

* By default, we expect computations to contain a single `Parameter`, which will be the input. When loading the Keras model, it still contains `Variable` ops, which are translated into `Parameters`. You will need to freeze the Keras model (e.g. [here](https://towardsdatascience.com/freezing-a-keras-model-c2e26cb84a38), or our [MLP example](https://github.com/NervanaSystems/he-transformer/blob/master/examples/MNIST/MLP/train.py#L60)) to turn the `Parameters` into `Constant` ops.

* The `ArgMax` op at the end is unsupported.
