### ISSUE TITLE
Issue with 'make build_and_test_he_transformer' using Docker image

### ISSUE THREAD

**Issue by mlayou** [NervanaSystems/he-transformer#238]
Hello,
I'm using the Docker method to build and test he-transformer. 
I have downloaded the content of the **he-transformer/docker/** directory, and run the two following command lines: 
**`make build_docker_image`
`make build_and_test_he_transformer`**

The first one **`make build_docker_image`** completed successfully without any issues. 

The second **`make build_and_test_he_transformer`**, on the other hand, completed the two first targets **`build`** and **`unit_tests`** successfully, and then failed on the third target **`python_integration`**. Below is the error trace I got. 

```
[----------] Global test environment tear-down
[==========] 186 tests from 3 test cases ran. (45569 ms total)
[  PASSED  ] 186 tests.

  YOU HAVE 2 DISABLED TESTS

/home/he-transformer
Running python examples
python: can't open file 'axpy.py': [Errno 2] No such file or directory
Makefile:19: recipe for target 'build_and_test_he_transformer' failed
make: *** [build_and_test_he_transformer] Error 2
```
Here's also the code of the **`python_integration()`** function in **`build_and_test_he_transformer.sh`**

```
python_integration()
{
    echo 'Running python examples'
    cd examples
    python axpy.py
    NGRAPH_TF_BACKEND=HE_SEAL python axpy.py
    cd MNIST-Cryptonets
    NGRAPH_HE_SEAL_CONFIG=../../test/model/he_seal_ckks_config_N13_L7.json \
        NGRAPH_TF_BACKEND=HE_SEAL \
        NGRAPH_ENCRYPT_DATA=1 \
        python test.py --batch_size=128
}
```
The runtime trace above does not complain about **`cd examples`**, but then it cannot find the 
**`axpy.py`** in that directory or anywhere in its path. Any idea how to fix this? 

By the way, I have to run a shell on the **`he-transformer`** container (**`docker run -it he_transformer /bin/bash`**) to find the location of the axpy.py file inside the he-transformer image, but I could not find any code from he-transformer on the image. (See below)
Isn't the  **`make build_docker_image`**  command supposed to persist the he-transformer build (i.e., the executable binary and python files etc.) on the docker image? In other words, Am I not supposed to find those files when I log into the docker image?
Thank you for your help.

```
root@e59568a260f6:/home# ls -last
total 8
4 drwxr-xr-x 1 root root 4096 Jul 19 14:59 ..
4 drwxr-xr-x 2 root root 4096 Apr 12  2016 .
root@e59568a260f6:/home# ls -last /
total 164736
     0 drwxr-xr-x   5 root root       360 Jul 19 14:59 dev
     0 dr-xr-xr-x 351 root root         0 Jul 19 14:59 proc
     4 drwxr-xr-x   1 root root      4096 Jul 19 14:59 .
     4 drwxr-xr-x   1 root root      4096 Jul 19 14:59 ..
     0 -rwxr-xr-x   1 root root         0 Jul 19 14:59 .dockerenv
     4 drwxr-xr-x   1 root root      4096 Jul 19 14:59 etc
     0 dr-xr-xr-x  13 root root         0 Jul 18 18:02 sys
     4 drwx------   1 root root      4096 Jul 18 15:37 root
     4 drwxrwxrwt   1 root root      4096 Jul 18 15:36 tmp
     4 drwxr-xr-x   1 root root      4096 Jul 18 15:36 lib
     4 drwxr-xr-x   1 root root      4096 Jul 18 15:36 run
     4 drwxr-xr-x   1 root root      4096 Jul 18 15:35 sbin
     4 drwxr-xr-x   1 root root      4096 Jul 18 15:35 bin
     4 drwxr-xr-x   1 root root      4096 Jun 10 20:41 var
     4 drwxr-xr-x   2 root root      4096 Jun 10 20:41 lib64
     4 drwxr-xr-x   2 root root      4096 Jun 10 20:40 media
     4 drwxr-xr-x   2 root root      4096 Jun 10 20:40 mnt
     4 drwxr-xr-x   2 root root      4096 Jun 10 20:40 opt
     4 drwxr-xr-x   2 root root      4096 Jun 10 20:40 srv
     4 drwxr-xr-x   1 root root      4096 Jun 10 20:40 usr
164664 -rw-r--r--   1 root root 168610096 Dec 19  2018 bazel_0.21.0-linux-x86_64.deb
     4 drwxr-xr-x   2 root root      4096 Apr 12  2016 boot
     4 drwxr-xr-x   2 root root      4096 Apr 12  2016 home
root@e59568a260f6:/home# find / -name *he-transformer*
root@e59568a260f6:/home# 
```

**Comment by fboemer** [comment]
Try renaming `axpy.py => ax.py` in the [Dockerfile](https://github.com/NervanaSystems/he-transformer/blob/master/docker/build_and_test_he_transformer.sh#L52-L53).
