### ISSUE TITLE
Does he-transformer have client-server capabilities for for training neural networks?

### ISSUE THREAD

**Issue by jayavanth** [NervanaSystems/he-transformer#253]
I'm looking at the MNIST example and I was wondering if he-transform can be used like a client-server. In this scenario, client wants to train an encrypted model with the encrypted data on the server and after training, the server will respond to requests to run forward prop on encrypted test data.

Is this feature already in he-transformer? If not, how should I go about implementing it? Also, do I need to take care of sending things over back to the client (which decrypts and then encrypts) during training so as to have a reasonable noise budget?

**Comment by fboemer** [comment]
We don't currently support training. We haven't looked into this, so aren't able to advise how to implement it. I suspect this is a quite involved task. The best place to start would be to figure out how different ngraph backends support training.

You would most likely need to send data back and forth to have a reasonable noise budget.
