### ISSUE TITLE
'no module named numpy' during 'make install'

### ISSUE THREAD

**Issue by zzd1024** [NervanaSystems/he-transformer#267]
![WechatIMG44](https://user-images.githubusercontent.com/54406312/63530864-e5292f00-c539-11e9-8b99-a369e12c5ea3.jpeg)
Get an error during 'make install', it says 'no module named numpy', but numpy has already been installed, import numpy on the python didn't report error. My system has installed python3.7, anaconda, and mac installed python2.7 by default. The build project uses python3.7. I have tried to uninstall conda's numpy, it doesn't work either. Does anyone know the reason for this problem?

**Comment by zzd1024** [comment]
/Users/zhaozhendong/Desktop/WechatIMG44.jpeg

**Comment by fboemer** [comment]
We don't support Mac. I'd recommend taking a look at the [Docker builds](https://github.com/NervanaSystems/he-transformer/tree/master/contrib/docker)
