### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by dksuper** [NervanaSystems/he-transformer#268]
Hi , I have get the error when I doingt the [make install step](https://github.com/NervanaSystems/he-transformer#1-build-he-transformer) , the error message is:

> Exception: Error running command: bazel build --config=opt --config=noaws --config=nohdfs --config=noignite --config=nokafka --config=nonccl //tensorflow/tools/pip_package:build_pip_package

does anyone can help? 

thank you!

**Comment by zzd1024** [comment]
How did you solve "FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv': 'virtualenv'" this error? I have the same situation
