### ISSUE TITLE
How do compute biases for merged layers.

### ISSUE THREAD

**Issue by Musawar71** [NervanaSystems/he-transformer#270]
I am working on cryptonets, the issue for me is to generate biases while merging layers, so can you please elaborate the method for generate biases

**Comment by fboemer** [comment]
Currently, we only merge layers with no biases. The composition of linear layers with biases is also a linear layer with a bias, so this is possible as well. For example,

`W_2(W_1x + b_1) + b2 => W_2W_1x + (W_2b_1 + b_2)`
