### ISSUE TITLE
Tests failed while running the c++ test units

### ISSUE THREAD

**Issue by nyeinsoe26** [NervanaSystems/he-transformer#288]
![Screenshot from 2019-10-30 05-54-04](https://user-images.githubusercontent.com/54412199/67812343-efd3e780-fad9-11e9-9901-62536b3cb31e.png)
When i ran the c++ test units, I am having these errors. Do anyone have any idea on how to fix this issue?

**Comment by fboemer** [comment]
You can run the individual tests `./test/unit-test --gtest_filter="HE_SEAL.batch_norm_inference*"` to see the reason. This should have been fixed recently, so pulling from master should resolve the issue.
